const cities = [

    // Tamil Nadu

    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Hosur",
    "Kallakurichi",
    "Kanchipuram",
    "Kanyakumari",
    "Karaikudi",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Mayiladuthurai",
    "Mettupalayam",
    "Nagapattinam",
    "Nagercoil",
    "Namakkal",
    "Ooty",
    "Palani",
    "Perambalur",
    "Pollachi",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Rajapalayam",
    "Salem",
    "Sivagangai",
    "Sivakasi",
    "Tambaram",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupathur",
    "Tiruppur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Udhagamandalam",
    "Vellore",
    "Viluppuram",
    "Virudhunagar"

];

export default cities;